FizzBuzzApplication/FizzBuzzApplication/Models/FizzBuzzModel.cs
// <copyright file="FizzBuzzModel.cs" company="Test"> 
// 2017</copyright> 
// <summary> 
// FizzBuzz Model 
// </summary> 
namespace FizzBuzzApplication.Models
{
    using System.ComponentModel.DataAnnotations;
    using PagedList;

    /// <summary>
    /// Fizz Buzz Model
    /// </summary>
    public class FizzBuzzModel
    {
        /// <summary>
        /// Gets or sets the number
        /// </summary>
        [Required(ErrorMessage = "Input Required")]
        [Display(Name = "Please Enter Number")]
        [Range(1, 1000, ErrorMessage = "The input value must be between 1 and 1000")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Please enter a numeric value")]
        public int? Number { get; set; }

        /// <summary>
        /// Gets or sets the fizz buzz list
        /// </summary>
        public IPagedList<string> FizzBuzzList { get; set; }

        /// <summary>
        /// Gets or sets the page number
        /// </summary>
        public int? Page { get; set; }
    }
}

FizzBuzzApplication/FizzBuzzApplication/Controllers/FizzBuzzController.cs
// <copyright file="FizzBuzzController.cs" company="Test"> 
// 2017</copyright> 
// <summary> 
// FizzBuzz Controller 
// </summary> 
namespace FizzBuzzApplication.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using FizzBuzzApplication.Models;
    using FizzBuzzServices.Interfaces;
    using PagedList;

    /// <summary>
    /// Fizz Buzz Controller
    /// </summary>
    public class FizzBuzzController : Controller
    {
        /// <summary>
        /// Page Size
        /// </summary>
        private const int PageSize = 20;

        /// <summary>
        /// IFizzBuzzService Instance
        /// </summary>
        private readonly IFizzBuzzService fizzBuzzService;

        /// <summary>
        /// Initializes a new instance of the <see cref="FizzBuzzController"/> class
        /// </summary>
        /// <param name="fizzBuzzService">fizzBuzzService Instance</param>
        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            this.fizzBuzzService = fizzBuzzService;
        }

        /// <summary>
        /// Index action
        /// </summary>
        /// <returns>Index view</returns>
        [HttpGet]
        public ActionResult Index()
        {
            ModelState.Clear();
            return this.View("Index");
        }

        /// <summary>
        /// action to get fizz buzz list
        /// </summary>
        /// <param name="fizzBuzzModel">fizz Buzz Model</param>
        /// <returns>Index view with updated model</returns>
        [HttpGet]
        public ActionResult GetList(FizzBuzzModel fizzBuzzModel)
        {
            if (ModelState.IsValid)
            {
                var fizzbuzzList = this.fizzBuzzService.GetFizzBuzzList(fizzBuzzModel.Number ?? 0);
                if ((fizzBuzzModel.Page ?? 1) * PageSize > fizzbuzzList.Count())
                {
                    fizzBuzzModel.Page = this.GetMaxPageNumber(fizzbuzzList.Count());
                }

                fizzBuzzModel.FizzBuzzList = fizzbuzzList.ToPagedList(fizzBuzzModel.Page ?? 1, PageSize);
            }

            return this.View("Index", fizzBuzzModel);
        }

        /// <summary>
        /// Method to get max page number of paged list
        /// </summary>
        /// <param name="totalItems">total items in list</param>
        /// <returns>max page number</returns>
        private int GetMaxPageNumber(double totalItems)
        {
            var mxPageSize = totalItems / PageSize;
            return (int)Math.Ceiling(mxPageSize);
        }
    }
}

FizzBuzzApplication/FizzBuzzApplication/Views/FizzBuzz/Index.cshtml
@{
    ViewBag.Title = "Fizz Buzz Application";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model FizzBuzzApplication.Models.FizzBuzzModel
@using PagedList.Mvc;
<div class="FizzBuzzApp">
    <div>
        <h2>Fizz Buzz Application</h2>
        @using (@Html.BeginForm("GetList", "FizzBuzz", FormMethod.Get))
        {
            <div>
                @Html.ValidationSummary(true)
                <div>
                    <div>
                        @Html.LabelFor(m => m.Number)
                        @Html.TextBoxFor(m => m.Number)
                        @Html.ValidationMessageFor(m => m.Number, "", new { @class = "validationMsg" })
                    </div>
                    <div>
                    </div>
                </div>
                <input type="submit" value="Get List" />
            </div>
        }
    </div>
    <div class="fizzbuzzList">
        @if (Model != null && Model.FizzBuzzList != null && Model.FizzBuzzList.Any())
        { 
            <ul>
                @foreach (var item in Model.FizzBuzzList)
                {
                    <li>
                        @FizzBuzzHelpers.ApplyStyleByWord(item)
                    </li>
                }
            </ul>
            <p>
                @Html.PagedListPager((Model.FizzBuzzList), page => Url.Action("GetList", new { Page = page, Number = Model.Number }), PagedList.Mvc.PagedListRenderOptions.ClassicPlusFirstAndLast)
            </p>
        }
    </div>
</div>

FizzBuzzApplication/FizzBuzzApplication/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @RenderSection("scripts", required: false)
</body>
</html>